gogo-cockpit/config/routes.rb
Rails.application.routes.draw do

  resources :invites
  resources :invites do
    member do
      post 'grant'
    end
  end

  resources :apps do
    resources :owners, controller: 'ownerships'
    resources :placements
  end

  resources :ownerships
  resources :placements do
    resources :campaigns do 
      resources :assets
    end
  end
  resources :campaigns, :only => [:index, :show, :edit, :update, :destroy]
  post "campaigns/:id/toggle" => "campaigns#toggle", :as => :toggle_campaign
  resources :assets, :only => [:show, :edit, :update, :destroy]
  
  get 'placements/:placement_id/assets/modulo/:int' => 'placements#modulo'
  
  devise_for :users, :controllers => { 
    :registrations => "registrations", 
    :omniauth_callbacks => "omniauth_callbacks#google_oauth2",
  }
  devise_scope :users do
    post "users/:id/toggle" => "users#toggle", :as => :toggle_user
    get "users/index" => "users#index"
    delete "users/:id" => "users#destroy"
  end
  resources :users

  get 'assets/:id/raw' => 'assets#raw', :as => :raw_asset

  root 'home#index'

end

gogo-cockpit/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable, :omniauthable, :confirmable

	has_many :apps

	def self.from_omniauth(auth)
		where(:auth_provider => auth.provider, :auth_uid => auth.uid).first_or_create do |user|
			user.email = auth.info.email
			user.auth_provider = auth.provider
			user.auth_uid = auth.uid
			user.auth_token = Devise.friendly_token[0,20]
			user.name = auth.info.name
			user.image_url = auth.info.image
			user.role = "base" unless user.role?
		end
	end
	

	def self.new_with_session(params, session)
    	super.tap do |user|
			unless session["devise.google_data"].nil?
				puts session["devise.google_data"].to_hash
				data = session["devise.google_data"]
				user.email = data["info"]["email"]
				user.auth_provider = data["provider"]
				user.auth_uid = data["uid"]
				user.auth_token = Devise.friendly_token[0,20]
				user.name = data["info"]["name"]
				user.image_url = data["info"]["image"]
				user.role = "base"
				user.is_active = true
			end
	    end
	end

    def admin?
    	self.role == "admin"
    end

    def base?
    	self.role == "base"
    end

    def is_active?
    	self.is_active == true
    end

end

gogo-cockpit/app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource

	def index 
		@users = User.all
	end	

	def toggle
		@user = User.find(params[:id])
		@user.is_active = !@user.is_active
		@user.save() 
		redirect_to users_path
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

end

gogo-cockpit/app/helpers/users_helper.rb
module UsersHelper
end

gogo-cockpit/app/views/users/index.html.erb
<h1>Users</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Active</th>
    <th>Created</th>
    <th>Confirmed</th>
    <th>Role</th>
    <th colspan="3">Actions</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= !!user.is_active %> <% if user != current_user %><%= raw "(" +  link_to('Toggle', toggle_user_path(user), method: :post) + ")" %><% end %></td>
      <td><%= user.created_at %></td>
      <td><%= user.confirmed_at %></td>
      <td><%= user.role %></td>
      <td><%= link_to 'Show', [user], method: :get %></td>
      <td><%= link_to 'Remove', [user], method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Invite user', new_invite_path, :class => "btn btn-default" %>