gogo-cockpit/config/routes.rb
Rails.application.routes.draw do

  resources :invites
  resources :invites do
    member do
      post 'grant'
    end
  end

  resources :apps do
    resources :owners, controller: 'ownerships'
    resources :placements
  end

  resources :ownerships
  resources :placements do
    resources :campaigns do 
      resources :assets
    end
  end
  resources :campaigns, :only => [:index, :show, :edit, :update, :destroy]
  post "campaigns/:id/toggle" => "campaigns#toggle", :as => :toggle_campaign
  resources :assets, :only => [:show, :edit, :update, :destroy]
  
  get 'placements/:placement_id/assets/modulo/:int' => 'placements#modulo'
  
  devise_for :users, :controllers => { 
    :registrations => "registrations", 
    :omniauth_callbacks => "omniauth_callbacks#google_oauth2",
  }
  devise_scope :users do
    post "users/:id/toggle" => "users#toggle", :as => :toggle_user
    get "users/index" => "users#index"
    delete "users/:id" => "users#destroy"
  end
  resources :users

  get 'assets/:id/raw' => 'assets#raw', :as => :raw_asset

  root 'home#index'

end

gogo-cockpit/app/models/placement.rb
class PlacementValidator < ActiveModel::Validator
	def validate(record)
		if record.name.nil? && record.name.length > 0
			record.errors[:base] << "Placement must have a name"
		end
	end
end

class Placement < ActiveRecord::Base
	has_many :campaigns
	belongs_to :app

	include ActiveModel::Validations
	validates_with PlacementValidator

	def any_active_campaign_in_duration(start, ende)
		campaigns = self.campaigns.select { |c| if c.is_active && (c.start <= ende && c.end >= start) then c end }
		return campaigns[0]
	end
end

gogo-cockpit/app/controllers/placements_controller.rb
class PlacementsController < ApplicationController
	load_and_authorize_resource
	check_authorization :unless => :modulo

	def new
		@app = App.find(params[:app_id])
		@placement = Placement.new()
	end

	def create
		@app = App.find(params[:app_id])
		@placement = @app.placements.create(placement_params)
		if @placement.errors.size > 0
			render "new"
		else
			redirect_to placement_path(@placement)
		end
	end

	def show
		respond_to do |format|
			format.html { 
				cache_key = request.original_fullpath
				puts cache_key
				content = Rails.cache.read(cache_key)
				if content.nil?
				  	@placement = Placement.find(params[:id])
				  	content = render_to_string(:template => "placements/show.html.erb")
					Rails.cache.write(cache_key, content, { :expires_in => 10.seconds })
				end
				render inline: content
			}
			format.json { 
				render inline: ActiveSupport::JSON.encode(Placement.find(params[:id])) 
			}
		end
	end

	def index
		unless params[:app_id].nil?
			@placements = App.find(params[:app_id]).placements
		else
			@placements = Placement.all
		end
	end

	def edit
		 @placement = Placement.find(params[:id])
	end

	def update
		@placement = Placement.find(params[:id])
		if @placement.update(placement_params)
			redirect_to(@placement)
		else
			render :edit
		end
	end

	def destroy
		@placement = Placement.find(params[:id])
		@placement.campaigns.each do |campaign|
			campaign.destroy
		end
		@placement.destroy
		redirect_to :back
	end

	def modulo
		placement = Placement.find(params[:placement_id])
		campaign = (placement.campaigns.select {|c| c.start <= DateTime.now && c.end >= DateTime.now })[0]
		if campaign.nil? || !campaign.assets.any?
			head :no_content
			return 
		end
		shares = []
		campaign.assets.each_with_index do |asset, idx|
			puts asset.inspect
			if asset.weight.nil? then asset.weight = 1 end
			(0..asset.weight-1).step(1) do |n|
				shares << idx
			end
		end
		idx = shares[params[:int].to_i % shares.length]
		asset = campaign.assets[idx]
		authorize! :modulo, asset
		headers["X-Num-Variations"] = "#{campaign.assets.length}"
		headers["X-Campaign"] = campaign.name
		headers["X-Content-Tag"] = asset.name
		expires_in [30*60, ((campaign.end - DateTime.now)*24*60*60).to_i].min.seconds
		send_file asset.filepath, :disposition => 'inline'
	end

	private

	def placement_params
		params.require(:placement).permit(:name, :description)
	end

end

gogo-cockpit/app/helpers/placements_helper.rb
module PlacementsHelper
end

gogo-cockpit/app/views/placements/_form.html.erb
<%= form_for ([@app, @app.placements.build]) do |f| %>
  <% if @placement.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@placement.errors.count, "error") %> prohibited
      this placement from being saved:</h2>
    <ul>
    <% @placement.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

gogo-cockpit/app/views/placements/edit.html.erb
<h1>Edit Placement</h1>

<%= render 'form' %>

<%= link_to 'Back', placements_path %>

gogo-cockpit/app/views/placements/new.html.erb
<h1>New Placement</h1>

<%= render 'form' %>

<%= link_to 'Back', placements_path %>

gogo-cockpit/app/views/placements/show.html.erb
<ul class="breadcrumb">
<li><%= link_to "Apps", apps_path %>  
<li><%= link_to "App: #{@placement.app.name}", @placement.app %>
<li class="active">Placement: <%= @placement.name %></li>
</ul>

<div class="page-header"><h1><%= @placement.name %><br /><small>Placement</small></h1></div>

<table class="table-condensed">
  <tr>
    <td><strong>Description:</strong></td>
    <td><%= @placement.description %></td>
  </tr>
</table>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Campaigns</div>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Start</th>
    <th>End</th>
    <th>State</th>
  </tr>
 
  <% @placement.campaigns.each do |campaign| %>
  <% active = campaign.start < DateTime.now && campaign.end > DateTime.now %>
    <tr>
      <td><%= link_to campaign.name, [campaign], method: :get %></td>
      <td><%= campaign.start %></td>
      <td><%= campaign.end %></td>
      <td><%= !!campaign.is_active ? "active" : "inactive" %> <%= raw "(" +  link_to('Toggle', toggle_campaign_path(campaign), method: :post) + ")" %></td>
    </tr>
  <% end %>
</table>
</div>
<%= link_to 'Add new campaign', new_placement_campaign_path(@placement), :class => "btn btn-default" %>
</div>