gogo-cockpit/config/routes.rb
Rails.application.routes.draw do

  resources :invites
  resources :invites do
    member do
      post 'grant'
    end
  end

  resources :apps do
    resources :owners, controller: 'ownerships'
    resources :placements
  end

  resources :ownerships
  resources :placements do
    resources :campaigns do 
      resources :assets
    end
  end
  resources :campaigns, :only => [:index, :show, :edit, :update, :destroy]
  post "campaigns/:id/toggle" => "campaigns#toggle", :as => :toggle_campaign
  resources :assets, :only => [:show, :edit, :update, :destroy]
  
  get 'placements/:placement_id/assets/modulo/:int' => 'placements#modulo'
  
  devise_for :users, :controllers => { 
    :registrations => "registrations", 
    :omniauth_callbacks => "omniauth_callbacks#google_oauth2",
  }
  devise_scope :users do
    post "users/:id/toggle" => "users#toggle", :as => :toggle_user
    get "users/index" => "users#index"
    delete "users/:id" => "users#destroy"
  end
  resources :users

  get 'assets/:id/raw' => 'assets#raw', :as => :raw_asset

  root 'home#index'

end

gogo-cockpit/app/views/apps/_form.html.erb
<%= form_for @app do |f| %>
  <% if @app.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@app.errors.count, "error") %> prohibited
      this app from being saved:</h2>
    <ul>
    <% @campaign.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit "Save", :class => "btn btn-default" %>
    <a href="javascript:history.back()" class="btn btn-default">Cancel</a>
  </p>
<% end %>

gogo-cockpit/app/views/apps/edit.html.erb
<h1>Edit App</h1>

<%= render 'form' %>

gogo-cockpit/app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th colspan="3">Actions</th>
  </tr>
 
  <% @apps.each do |app| %>
    <tr>
      <td><%= app.name %></td>
      <td><%= link_to 'Show', [app], method: :get %></td>
      <td><%= link_to 'Edit', edit_app_path(app) %></td>
      <td><%= link_to 'Remove', [app], method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Add new app', new_app_path() %>

gogo-cockpit/app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

gogo-cockpit/app/views/apps/show.html.erb
<ul class="breadcrumb">
<li><%= link_to "Apps", apps_path %> <span class="divider"></span></li>
<li class="active">App: <%= @app.name %></li>
</ul>

<div class="page-header">
  <h1><%= @app.name %><br /><small>App</small></h1>
</div>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Placements</div>

  <table class="table">
    <tr>
      <th>Name</th>
      <th colspan="2">Actions</th>
    </tr>
   
    <% @app.placements.each do |placement| %>
      <tr>
        <td><%= placement.name %></td>
        <td><%= link_to 'Show', [placement], method: :get %></td>
        <td><%= link_to 'Remove', [placement], method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </table>
</div>
<%= link_to 'Add new placement', new_app_placement_path(@app), :class => "btn btn-default" %>
<%= link_to 'Edit app', edit_app_path(@app), :class => "btn btn-default" %>